version: '3'

services:
  api:
    container_name: api
    env_file: ./nest-backend/.env
    restart: unless-stopped
    build:
      context: ./nest-backend
      dockerfile: ./Dockerfile
    ports:
      - "8079:3001"
    networks:
      - backend
  frontend:
    container_name: frontend
#    env_file: ./react-frontend/.env
    restart: unless-stopped
    build:
      context: ./react-frontend
      dockerfile: ./Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8079/
    ports:
      - "8080:3000"
    networks:
      - backend
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    networks:
      - backend
      
networks:
  backend:
