interface CardObject {
    cardPosition: number, //the position of the card in the container
    cardNumber: number | undefined //the number generated by the backend algorithm assigned to this card
    flipCallback: Function
    isFlipped: boolean
    isVisible: boolean
}